---
sudo: yes

services:
  - docker

env:
  matrix:
    - image=sleepert/bastion-ubuntu
      init=/lib/systemd/systemd
      run_opts="--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  - docker pull $image

script:
  - container_id=$(mktemp)
  - docker run --detach --volume="${PWD}":/etc/bless:ro $run_opts $image "$init" > "$container_id"
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/bless/bastion/ansible/playbook.yml
    --syntax-check

  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/bless/bastion/ansible/playbook.yml

  - idempotence=$(mktemp)
  - >
    docker exec "$(cat ${container_id})"
    ansible-playbook /etc/bless/bastion/ansible/playbook.yml
    | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
