---
sudo: yes

env:
  - distro: ubuntu1804
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  - docker pull geerlingguy/docker-$(distro)-ansible:latest

script:
  - container_id = $(mktemp)
  - 'docker run --detach --volume="${PWD}":/etc/bless:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/bless/bastion/playbook.yml
    --syntax-check

  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/bless/bastion/playbook.yml

  - idempotence = $(mktemp)
  - >
    docker exec "$(cat ${container_id})"
    ansible-playbook /etc/bless/bastion/playbook.yml
    | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
