---

- name: make .ssh directory
  file:
    path: "{{ ssh_path }}"
    state: directory
    group: root
    owner: root
    mode: 0700

- name: ensure empty authorized_keys file
  copy:
    content: ""
    dest: "{{ ssh_path }}/authorized_keys"
    force: no
    group: root
    owner: root
    mode: 0600

- name: copy bless_client
  copy:
    src: files/bless_client.py
    dest: "{{ skel_path }}/bless_client.py"
    mode: 0700

- name: create bash aliases
  copy:
    src: files/bash_aliases
    dest: "{{ skel_path }}/.bash_aliases"
    owner: root
    group: root
    mode: 0400

- name: create temporary ssh key
  command: ssh-keygen -t rsa -b 4096 -f {{ ssh_path }}/{{ bless_key }} -N '' -C ''
  args:
    creates: "{{ ssh_path }}/{{ bless_key }}"#

- name: make public key
  command: ssh-keygen -y -f {{ ssh_path }}/{{ bless_key }} > {{ ssh_path }}/{{ bless_key }}.pub
  args:
    creates: "{{ ssh_path }}/{{ bless_key }}.pub"#

- name: create certificate file
  copy:
    content: ""
    dest: "{{ ssh_path }}/{{ bless_key }}-cert.pub"
    force: no
    group: root
    owner: root
    mode: 0600

- name: certificate symlink
  file:
    src: "{{ ssh_path }}/{{ bless_key }}-cert.pub"
    dest: "{{ ssh_path }}/{{ bless_key }}-cert"
    state: link
